# Generated by Django 2.2 on 2020-10-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201008_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='type',
            field=models.CharField(choices=[('register', 'Регистрация'), ('password_reset', 'Восстановление пароля')], default='register', max_length=20, verbose_name='Тип токена'),
        ),
    ]
