# Generated by Django 2.2 on 2020-07-29 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_article_publish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
        ),
    ]
