# Generated by Django 2.2 on 2020-10-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_article_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='webapp.Article', verbose_name='Статья'),
        ),
    ]
